import Link from "next/link";

export const revalidate = 31536000;

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50 flex flex-col">
      <div className="flex-1 flex items-center justify-center px-4 py-8">
        <div className="w-full max-w-4xl">
          <div className="mb-6 text-center">
            <Link
              href="/"
              className="inline-flex items-center text-slate-600 hover:text-slate-800 transition-colors"
            >
              <svg
                className="w-4 h-4 mr-2"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M15 19l-7-7 7-7"
                />
              </svg>
              Back to Home
            </Link>
          </div>

          <div className="text-center mb-8">
            <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-slate-800 mb-4">
              Privacy Policy (v2)
            </h1>
            <p className="text-slate-600">Last Updated: April 1, 2026</p>
          </div>

          <div className="bg-white rounded-2xl shadow-lg border border-slate-200 overflow-hidden">
            <div className="p-8 space-y-8">
              <section>
                <h2 className="text-2xl font-semibold text-slate-800 mb-4">
                  1. Versioning & Previous Policy
                </h2>
                <p className="text-slate-600 leading-relaxed">
                  This is Privacy Policy version 2. The previous policy is preserved and available here:{" "}
                  <Link href="/privacy/v1" className="text-blue-600 hover:underline">
                    Privacy Policy v1
                  </Link>
                  .
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-slate-800 mb-4">
                  2. Scope of This Policy
                </h2>
                <p className="text-slate-600 leading-relaxed">
                  This policy applies to this website and its student directory features. It explains what information is
                  displayed, how it is used, how it is stored, and how to contact the maintainer.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-slate-800 mb-4">
                  3. Data We Display
                </h2>
                <p className="text-slate-600 leading-relaxed mb-4">
                  We maintain limited directory data fields, including:
                </p>
                <ul className="list-disc list-inside text-slate-600 space-y-2 ml-4">
                  <li>Student Name</li>
                  <li>Student ID</li>
                  <li>Department</li>
                  <li>Admission Roll Number</li>
                  <li>Admission Merit Position</li>
                  <li>Batch Number</li>
                  <li>Academic Session</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-slate-800 mb-4">
                  4. Data Source
                </h2>
                <p className="text-slate-600 leading-relaxed">
                  The data was collected from publicly available internet PDFs/data and gathered into one place for easier
                  search and access.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-slate-800 mb-4">
                  5. Data Minimization
                </h2>
                <p className="text-slate-600 leading-relaxed">
                  This site is intended as a directory and does not intentionally collect sensitive personal data beyond
                  what is already publicly available in source materials used for compilation.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-slate-800 mb-4">
                  6. Storage & Security
                </h2>
                <p className="text-slate-600 leading-relaxed">
                  The site and directory database are hosted on Cloudflare D1. Appropriate security controls are used to
                  protect stored records and application access.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-slate-800 mb-4">
                  7. Analytics & Technical Logs
                </h2>
                <p className="text-slate-600 leading-relaxed">
                  Basic technical logs may be generated by hosting infrastructure for reliability and security monitoring.
                  This policy does not claim collection of private profile data outside the directory context.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-slate-800 mb-4">
                  8. Data Coverage Limitation
                </h2>
                <p className="text-slate-600 leading-relaxed">
                  CSE 2022 batch students are not fully present in this directory. Only around 10-12 student records from
                  that batch are currently available here.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-slate-800 mb-4">
                  9. Changes to This Policy
                </h2>
                <p className="text-slate-600 leading-relaxed">
                  This policy may be updated over time. New revisions will be published on this page with an updated date,
                  and previous policy versions may be retained for transparency.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-slate-800 mb-4">
                  10. Contact
                </h2>
                <p className="text-slate-600 leading-relaxed">
                  If you have any questions, email{" "}
                  <a
                    href="mailto:hello@sayed.page"
                    className="text-blue-600 hover:underline"
                  >
                    hello@sayed.page
                  </a>
                  .
                </p>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
